### ISSUE TITLE
Is this the official repo in future? Plz use English everywhere including the READMEs.

### ISSUE THREAD

**Issue by hsluoyz** [ComradeProgrammer/casbin-kubesphere-auth#1]

**Comment by ComradeProgrammer** [comment]
Don't worry. After your check and acceptance, I shall translate everything into English.

**Comment by hsluoyz** [comment]
@ComradeProgrammer there should be no other language in all commits.

**Comment by ComradeProgrammer** [comment]
I see. I will translate everything into English as soon as possible.

**Comment by hsluoyz** [comment]
Plz rewrite all existing commits to make sure every commit is English.
